os:
  - linux
language: python
sudo: true
python:
  - 2.7
cache:
  directories:
    - $HOME/.pip-cache/
    - /home/travis/virtualenv/python2.7
before_install:
    - sudo apt-get update
    - sudo apt-get install libportaudio-dev libportaudio0 libportaudio2 python-pyaudio espeak festival
install: 
    - pip install -r python_requirement.txt
    - pip install python-coveralls
    - pip install coverage
    - pip install flake8
    - pip install codecov
before_script:
    - flake8 RoboCop.py
    - git config --global user.email "olxboss@gmail.com"
    - git config --global user.name "Travis-CI"
script:
    - coverage run -m unittest discover
after_success:
    - coverage report
    - coveralls
    - codecov --token=b7bcdcc3-478d-4ccc-871c-5896bb4c7383
